// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCourses.Infrastructure.Layer.ContextConfiguration;

namespace OnlineCourses.Infrastructure.Layer.Migrations {
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineCourses.Domain.Layer.Entities.Course", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<double>("AverageAge");

                b.Property<int>("MaximumAge");

                b.Property<int>("MaximumSignatures");

                b.Property<int>("MinimumAge");

                b.Property<string>("Name")
                    .IsRequired();

                b.Property<Guid>("TeacherId");

                b.Property<int>("TotalSignatures");

                b.HasKey("Id");

                b.HasIndex("TeacherId");

                b.ToTable("Courses");
            });

            modelBuilder.Entity("OnlineCourses.Domain.Layer.Entities.Student", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int>("Age");

                b.Property<Guid>("CourseId");

                b.Property<string>("Name")
                    .IsRequired();

                b.HasKey("Id");

                b.HasIndex("CourseId");

                b.ToTable("Students");
            });

            modelBuilder.Entity("OnlineCourses.Domain.Layer.Entities.Teacher", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name")
                    .IsRequired();

                b.HasKey("Id");

                b.ToTable("Teachers");
            });

            modelBuilder.Entity("OnlineCourses.Domain.Layer.Entities.Course", b => {
                b.HasOne("OnlineCourses.Domain.Layer.Entities.Teacher", "Teacher")
                    .WithMany()
                    .HasForeignKey("TeacherId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("OnlineCourses.Domain.Layer.Entities.Student", b => {
                b.HasOne("OnlineCourses.Domain.Layer.Entities.Course", "Course")
                    .WithMany("Students")
                    .HasForeignKey("CourseId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}
